# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-29 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('taskid', models.AutoField(primary_key=True, serialize=False)),
                ('taskName', models.CharField(max_length=256)),
                ('isDone', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('doneAt', models.DateTimeField(null=True)),
            ],
        ),
    ]
