# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-29 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='doneAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
